name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed for gh-pages deployment
  pages: write # Needed for GitHub Pages
  id-token: write # Needed for GitHub Pages authentication

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Create CNAME file
        run: echo 'webfishing.kot.li' > ./dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CF_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE }}
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
